trigger:
  branches:
    exclude:
      - '*'

jobs:
- job: DeployVM
  displayName: 'Deploy Azure VM'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt-get update && sudo apt-get install terraform

    displayName: 'Install Terraform'

  - checkout: self

  - script: |
      cd path/to/terraform/files

      terraform init
      terraform plan -out=tfplan -input=false

      terraform apply -input=false tfplan

    displayName: 'Deploy Azure VM'
