# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- test4

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
     
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Test02'
    backendAzureRmResourceGroupName: 'TESTDEV'
    backendAzureRmStorageAccountName: 'testsorage959'
    backendAzureRmContainerName: 'testdev'
    backendAzureRmKey: 'Gn7+wkKMVYiDjfkm+WiJWgZLwvTv+3neKEiQVQo9huwGfbkqzdC/YSBF5lBEJ4SGyk8CL0Yloe7X+AStMIqYdg=='
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'validate'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Test02'