# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'DevTest'
      backendAzureRmResourceGroupName: 'TESTDEV'
      backendAzureRmStorageAccountName: 'testsorage959'
      backendAzureRmContainerName: 'testdev'
      backendAzureRmKey: 'testdev.state'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: 'DevTest'